# Generated by Django 3.2.9 on 2022-01-02 08:30

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XrayUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'X-Ray Uploads',
                'verbose_name_plural': 'X-Ray Uploads',
                'db_table': 'xray_uploads',
            },
        ),
        migrations.CreateModel(
            name='UploadResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(blank=True)),
                ('results', models.TextField()),
                ('result_image', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('xray_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploads.xrayupload')),
            ],
            options={
                'verbose_name': 'X-Ray Uploads Results',
                'verbose_name_plural': 'X-Ray Uploads Results',
                'db_table': 'xray_uploads_results',
            },
        ),
    ]
